import { Team, Game } from "@/types";

export const STICKERS_PER_TEAM = 20;

export const MOCK_TEAMS: Team[] = [
  { id: "CZE", name: "República Tcheca", code: "CZE", group: "A", flag: "🇨🇿" },
  { id: "KOR", name: "Coreia do Sul", code: "KOR", group: "A", flag: "🇰🇷" },
  { id: "MEX", name: "México", code: "MEX", group: "A", flag: "🇲🇽" },
  { id: "RSA", name: "África do Sul", code: "RSA", group: "A", flag: "🇿🇦" },
  { id: "BIH", name: "Bósnia e Herzegovina", code: "BIH", group: "B", flag: "🇧🇦" },
  { id: "CAN", name: "Canadá", code: "CAN", group: "B", flag: "🇨🇦" },
  { id: "QAT", name: "Catar", code: "QAT", group: "B", flag: "🇶🇦" },
  { id: "SUI", name: "Suíça", code: "SUI", group: "B", flag: "🇨🇭" },
  { id: "BRA", name: "Brasil", code: "BRA", group: "C", flag: "🇧🇷" },
  { id: "HAI", name: "Haiti", code: "HAI", group: "C", flag: "🇭🇹" },
  { id: "MAR", name: "Marrocos", code: "MAR", group: "C", flag: "🇲🇦" },
  { id: "SCO", name: "Escócia", code: "SCO", group: "C", flag: "🏴" },
  { id: "AUS", name: "Austrália", code: "AUS", group: "D", flag: "🇦🇺" },
  { id: "PAR", name: "Paraguai", code: "PAR", group: "D", flag: "🇵🇾" },
  { id: "TUR", name: "Turquia", code: "TUR", group: "D", flag: "🇹🇷" },
  { id: "USA", name: "Estados Unidos", code: "USA", group: "D", flag: "🇺🇸" },
  { id: "CIV", name: "Costa do Marfim", code: "CIV", group: "E", flag: "🇨🇮" },
  { id: "CUW", name: "Curaçao", code: "CUW", group: "E", flag: "🇨🇼" },
  { id: "ECU", name: "Equador", code: "ECU", group: "E", flag: "🇪🇨" },
  { id: "GER", name: "Alemanha", code: "GER", group: "E", flag: "🇩🇪" },
  { id: "JPN", name: "Japão", code: "JPN", group: "F", flag: "🇯🇵" },
  { id: "NED", name: "Países Baixos", code: "NED", group: "F", flag: "🇳🇱" },
  { id: "SWE", name: "Suécia", code: "SWE", group: "F", flag: "🇸🇪" },
  { id: "TUN", name: "Tunísia", code: "TUN", group: "F", flag: "🇹🇳" },
  { id: "BEL", name: "Bélgica", code: "BEL", group: "G", flag: "🇧🇪" },
  { id: "EGY", name: "Egito", code: "EGY", group: "G", flag: "🇪🇬" },
  { id: "IRN", name: "Irã", code: "IRN", group: "G", flag: "🇮🇷" },
  { id: "NZL", name: "Nova Zelândia", code: "NZL", group: "G", flag: "🇳🇿" },
  { id: "CPV", name: "Cabo Verde", code: "CPV", group: "H", flag: "🇨🇻" },
  { id: "ESP", name: "Espanha", code: "ESP", group: "H", flag: "🇪🇸" },
  { id: "KSA", name: "Arábia Saudita", code: "KSA", group: "H", flag: "🇸🇦" },
  { id: "URU", name: "Uruguai", code: "URU", group: "H", flag: "🇺🇾" },
  { id: "FRA", name: "França", code: "FRA", group: "I", flag: "🇫🇷" },
  { id: "IRQ", name: "Iraque", code: "IRQ", group: "I", flag: "🇮🇶" },
  { id: "NOR", name: "Noruega", code: "NOR", group: "I", flag: "🇳🇴" },
  { id: "SEN", name: "Senegal", code: "SEN", group: "I", flag: "🇸🇳" },
  { id: "ALG", name: "Argélia", code: "ALG", group: "J", flag: "🇩🇿" },
  { id: "ARG", name: "Argentina", code: "ARG", group: "J", flag: "🇦🇷" },
  { id: "AUT", name: "Áustria", code: "AUT", group: "J", flag: "🇦🇹" },
  { id: "JOR", name: "Jordânia", code: "JOR", group: "J", flag: "🇯🇴" },
  { id: "COD", name: "RD Congo", code: "COD", group: "K", flag: "🇨🇩" },
  { id: "COL", name: "Colômbia", code: "COL", group: "K", flag: "🇨🇴" },
  { id: "POR", name: "Portugal", code: "POR", group: "K", flag: "🇵🇹" },
  { id: "UZB", name: "Uzbequistão", code: "UZB", group: "K", flag: "🇺🇿" },
  { id: "CRO", name: "Croácia", code: "CRO", group: "L", flag: "🇭🇷" },
  { id: "ENG", name: "Inglaterra", code: "ENG", group: "L", flag: "🏴" },
  { id: "GHA", name: "Gana", code: "GHA", group: "L", flag: "🇬🇭" },
  { id: "PAN", name: "Panamá", code: "PAN", group: "L", flag: "🇵🇦" },
];

export const MOCK_STADIUMS = [
  "Estádio da Cidade do México (Cidade do México)",
  "MetLife Stadium (New York/New Jersey)",
  "SoFi Stadium (Los Angeles)",
  "Hard Rock Stadium (Miami)",
  "BC Place (Vancouver)",
  "Estádio de Toronto (Toronto)"
];

export const MOCK_GAMES: Game[] = [
  {
    id: "game_1",
    stage: "groups",
    group: "A",
    home_team_id: "MEX",
    away_team_id: "RSA",
    kickoff: "2026-06-11T16:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio da Cidade do México (Cidade do México)"
  },
  {
    id: "game_2",
    stage: "groups",
    group: "A",
    home_team_id: "KOR",
    away_team_id: "CZE",
    kickoff: "2026-06-11T23:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio Guadalajara (Guadalajara)"
  },
  {
    id: "game_3",
    stage: "groups",
    group: "B",
    home_team_id: "CAN",
    away_team_id: "BIH",
    kickoff: "2026-06-12T16:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Toronto (Toronto)"
  },
  {
    id: "game_4",
    stage: "groups",
    group: "D",
    home_team_id: "USA",
    away_team_id: "PAR",
    kickoff: "2026-06-12T22:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Los Angeles (Los Angeles)"
  },
  {
    id: "game_5",
    stage: "groups",
    group: "B",
    home_team_id: "QAT",
    away_team_id: "SUI",
    kickoff: "2026-06-13T16:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio da Área da Baía de São Francisco (São Francisco)"
  },
  {
    id: "game_6",
    stage: "groups",
    group: "C",
    home_team_id: "BRA",
    away_team_id: "MAR",
    kickoff: "2026-06-13T19:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Nova York/Nova Jersey (Nova York/Nova Jersey)"
  },
  {
    id: "game_7",
    stage: "groups",
    group: "C",
    home_team_id: "HAI",
    away_team_id: "SCO",
    kickoff: "2026-06-13T22:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Boston (Boston)"
  },
  {
    id: "game_8",
    stage: "groups",
    group: "D",
    home_team_id: "AUS",
    away_team_id: "TUR",
    kickoff: "2026-06-14T01:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "BC Place Vancouver (Vancouver)"
  },
  {
    id: "game_9",
    stage: "groups",
    group: "E",
    home_team_id: "GER",
    away_team_id: "CUW",
    kickoff: "2026-06-14T14:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Houston (Houston)"
  },
  {
    id: "game_10",
    stage: "groups",
    group: "F",
    home_team_id: "NED",
    away_team_id: "JPN",
    kickoff: "2026-06-14T17:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Dallas (Dallas)"
  },
  {
    id: "game_11",
    stage: "groups",
    group: "E",
    home_team_id: "CIV",
    away_team_id: "ECU",
    kickoff: "2026-06-14T20:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio da Filadélfia (Filadélfia)"
  },
  {
    id: "game_12",
    stage: "groups",
    group: "F",
    home_team_id: "SWE",
    away_team_id: "TUN",
    kickoff: "2026-06-14T23:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio Monterrey (Monterrey)"
  },
  {
    id: "game_13",
    stage: "groups",
    group: "H",
    home_team_id: "ESP",
    away_team_id: "CPV",
    kickoff: "2026-06-15T13:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Atlanta (Atlanta)"
  },
  {
    id: "game_14",
    stage: "groups",
    group: "G",
    home_team_id: "BEL",
    away_team_id: "EGY",
    kickoff: "2026-06-15T16:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Seattle (Seattle)"
  },
  {
    id: "game_15",
    stage: "groups",
    group: "H",
    home_team_id: "KSA",
    away_team_id: "URU",
    kickoff: "2026-06-15T19:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Miami (Miami)"
  },
  {
    id: "game_16",
    stage: "groups",
    group: "G",
    home_team_id: "IRN",
    away_team_id: "NZL",
    kickoff: "2026-06-15T22:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Los Angeles (Los Angeles)"
  },
  {
    id: "game_17",
    stage: "groups",
    group: "I",
    home_team_id: "FRA",
    away_team_id: "SEN",
    kickoff: "2026-06-16T16:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Nova York/Nova Jersey (Nova York/Nova Jersey)"
  },
  {
    id: "game_18",
    stage: "groups",
    group: "I",
    home_team_id: "IRQ",
    away_team_id: "NOR",
    kickoff: "2026-06-16T19:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Boston (Boston)"
  },
  {
    id: "game_19",
    stage: "groups",
    group: "J",
    home_team_id: "ARG",
    away_team_id: "ALG",
    kickoff: "2026-06-16T22:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Kansas City (Kansas City)"
  },
  {
    id: "game_20",
    stage: "groups",
    group: "J",
    home_team_id: "AUT",
    away_team_id: "JOR",
    kickoff: "2026-06-17T01:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio da Área da Baía de São Francisco (São Francisco)"
  },
  {
    id: "game_21",
    stage: "groups",
    group: "K",
    home_team_id: "POR",
    away_team_id: "COD",
    kickoff: "2026-06-17T14:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Houston (Houston)"
  },
  {
    id: "game_22",
    stage: "groups",
    group: "L",
    home_team_id: "ENG",
    away_team_id: "CRO",
    kickoff: "2026-06-17T17:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Dallas (Dallas)"
  },
  {
    id: "game_23",
    stage: "groups",
    group: "L",
    home_team_id: "GHA",
    away_team_id: "PAN",
    kickoff: "2026-06-17T20:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Toronto (Toronto)"
  },
  {
    id: "game_24",
    stage: "groups",
    group: "K",
    home_team_id: "UZB",
    away_team_id: "COL",
    kickoff: "2026-06-17T23:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio da Cidade do México (Cidade do México)"
  },
  {
    id: "game_25",
    stage: "groups",
    group: "A",
    home_team_id: "CZE",
    away_team_id: "RSA",
    kickoff: "2026-06-18T13:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Atlanta (Atlanta)"
  },
  {
    id: "game_26",
    stage: "groups",
    group: "B",
    home_team_id: "SUI",
    away_team_id: "BIH",
    kickoff: "2026-06-18T16:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Los Angeles (Los Angeles)"
  },
  {
    id: "game_27",
    stage: "groups",
    group: "B",
    home_team_id: "CAN",
    away_team_id: "QAT",
    kickoff: "2026-06-18T19:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "BC Place Vancouver (Vancouver)"
  },
  {
    id: "game_28",
    stage: "groups",
    group: "A",
    home_team_id: "MEX",
    away_team_id: "KOR",
    kickoff: "2026-06-18T22:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio Guadalajara (Guadalajara)"
  },
  {
    id: "game_29",
    stage: "groups",
    group: "D",
    home_team_id: "USA",
    away_team_id: "AUS",
    kickoff: "2026-06-19T16:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Seattle (Seattle)"
  },
  {
    id: "game_30",
    stage: "groups",
    group: "C",
    home_team_id: "SCO",
    away_team_id: "MAR",
    kickoff: "2026-06-19T19:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Boston (Boston)"
  },
  {
    id: "game_31",
    stage: "groups",
    group: "C",
    home_team_id: "BRA",
    away_team_id: "HAI",
    kickoff: "2026-06-19T21:30:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio da Filadélfia (Filadélfia)"
  },
  {
    id: "game_32",
    stage: "groups",
    group: "D",
    home_team_id: "TUR",
    away_team_id: "PAR",
    kickoff: "2026-06-20T00:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio da Área da Baía de São Francisco (São Francisco)"
  },
  {
    id: "game_33",
    stage: "groups",
    group: "F",
    home_team_id: "NED",
    away_team_id: "SWE",
    kickoff: "2026-06-20T14:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Houston (Houston)"
  },
  {
    id: "game_34",
    stage: "groups",
    group: "E",
    home_team_id: "GER",
    away_team_id: "CIV",
    kickoff: "2026-06-20T17:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Toronto (Toronto)"
  },
  {
    id: "game_35",
    stage: "groups",
    group: "E",
    home_team_id: "ECU",
    away_team_id: "CUW",
    kickoff: "2026-06-20T21:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Kansas City (Kansas City)"
  },
  {
    id: "game_36",
    stage: "groups",
    group: "F",
    home_team_id: "TUN",
    away_team_id: "JPN",
    kickoff: "2026-06-21T01:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio Monterrey (Monterrey)"
  },
  {
    id: "game_37",
    stage: "groups",
    group: "H",
    home_team_id: "ESP",
    away_team_id: "KSA",
    kickoff: "2026-06-21T13:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Atlanta (Atlanta)"
  },
  {
    id: "game_38",
    stage: "groups",
    group: "G",
    home_team_id: "BEL",
    away_team_id: "IRN",
    kickoff: "2026-06-21T16:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Los Angeles (Los Angeles)"
  },
  {
    id: "game_39",
    stage: "groups",
    group: "H",
    home_team_id: "URU",
    away_team_id: "CPV",
    kickoff: "2026-06-21T19:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Miami (Miami)"
  },
  {
    id: "game_40",
    stage: "groups",
    group: "G",
    home_team_id: "NZL",
    away_team_id: "EGY",
    kickoff: "2026-06-21T22:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "BC Place Vancouver (Vancouver)"
  },
  {
    id: "game_41",
    stage: "groups",
    group: "I",
    home_team_id: "NOR",
    away_team_id: "SEN",
    kickoff: "2026-06-22T21:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Nova York/Nova Jersey (Nova York/Nova Jersey)"
  },
  {
    id: "game_42",
    stage: "groups",
    group: "I",
    home_team_id: "FRA",
    away_team_id: "IRQ",
    kickoff: "2026-06-22T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio da Filadélfia (Filadélfia)"
  },
  {
    id: "game_43",
    stage: "groups",
    group: "J",
    home_team_id: "ARG",
    away_team_id: "AUT",
    kickoff: "2026-06-22T14:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Dallas (Dallas)"
  },
  {
    id: "game_44",
    stage: "groups",
    group: "J",
    home_team_id: "JOR",
    away_team_id: "ALG",
    kickoff: "2026-06-23T00:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio da Área da Baía de São Francisco (São Francisco)"
  },
  {
    id: "game_45",
    stage: "groups",
    group: "L",
    home_team_id: "ENG",
    away_team_id: "GHA",
    kickoff: "2026-06-23T17:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Boston (Boston)"
  },
  {
    id: "game_46",
    stage: "groups",
    group: "L",
    home_team_id: "PAN",
    away_team_id: "CRO",
    kickoff: "2026-06-23T20:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Toronto (Toronto)"
  },
  {
    id: "game_47",
    stage: "groups",
    group: "K",
    home_team_id: "POR",
    away_team_id: "UZB",
    kickoff: "2026-06-23T14:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Houston (Houston)"
  },
  {
    id: "game_48",
    stage: "groups",
    group: "K",
    home_team_id: "COL",
    away_team_id: "COD",
    kickoff: "2026-06-23T23:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio Guadalajara (Guadalajara)"
  },
  {
    id: "game_49",
    stage: "groups",
    group: "C",
    home_team_id: "SCO",
    away_team_id: "BRA",
    kickoff: "2026-06-24T19:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Miami (Miami)"
  },
  {
    id: "game_50",
    stage: "groups",
    group: "C",
    home_team_id: "MAR",
    away_team_id: "HAI",
    kickoff: "2026-06-24T19:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Atlanta (Atlanta)"
  },
  {
    id: "game_51",
    stage: "groups",
    group: "B",
    home_team_id: "SUI",
    away_team_id: "CAN",
    kickoff: "2026-06-24T16:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "BC Place Vancouver (Vancouver)"
  },
  {
    id: "game_52",
    stage: "groups",
    group: "B",
    home_team_id: "BIH",
    away_team_id: "QAT",
    kickoff: "2026-06-24T16:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Seattle (Seattle)"
  },
  {
    id: "game_53",
    stage: "groups",
    group: "A",
    home_team_id: "CZE",
    away_team_id: "MEX",
    kickoff: "2026-06-24T22:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio da Cidade do México (Cidade do México)"
  },
  {
    id: "game_54",
    stage: "groups",
    group: "A",
    home_team_id: "RSA",
    away_team_id: "KOR",
    kickoff: "2026-06-24T22:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio Monterrey (Monterrey)"
  },
  {
    id: "game_55",
    stage: "groups",
    group: "E",
    home_team_id: "CUW",
    away_team_id: "CIV",
    kickoff: "2026-06-25T17:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio da Filadélfia (Filadélfia)"
  },
  {
    id: "game_56",
    stage: "groups",
    group: "E",
    home_team_id: "ECU",
    away_team_id: "GER",
    kickoff: "2026-06-25T17:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Nova York/Nova Jersey (Nova York/Nova Jersey)"
  },
  {
    id: "game_57",
    stage: "groups",
    group: "F",
    home_team_id: "JPN",
    away_team_id: "SWE",
    kickoff: "2026-06-25T20:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Dallas (Dallas)"
  },
  {
    id: "game_58",
    stage: "groups",
    group: "F",
    home_team_id: "TUN",
    away_team_id: "NED",
    kickoff: "2026-06-25T20:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Kansas City (Kansas City)"
  },
  {
    id: "game_59",
    stage: "groups",
    group: "D",
    home_team_id: "TUR",
    away_team_id: "USA",
    kickoff: "2026-06-25T23:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Los Angeles (Los Angeles)"
  },
  {
    id: "game_60",
    stage: "groups",
    group: "D",
    home_team_id: "PAR",
    away_team_id: "AUS",
    kickoff: "2026-06-25T23:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio da Área da Baía de São Francisco (São Francisco)"
  },
  {
    id: "game_61",
    stage: "groups",
    group: "G",
    home_team_id: "BEL",
    away_team_id: "NZL",
    kickoff: "2026-06-27T00:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Seattle (Seattle)"
  },
  {
    id: "game_62",
    stage: "groups",
    group: "G",
    home_team_id: "IRN",
    away_team_id: "EGY",
    kickoff: "2026-06-27T00:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "BC Place Vancouver (Vancouver)"
  },
  {
    id: "game_63",
    stage: "groups",
    group: "H",
    home_team_id: "ESP",
    away_team_id: "URU",
    kickoff: "2026-06-26T21:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio da Cidade do México (Cidade do México)"
  },
  {
    id: "game_64",
    stage: "groups",
    group: "H",
    home_team_id: "CPV",
    away_team_id: "KSA",
    kickoff: "2026-06-26T21:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio Guadalajara (Guadalajara)"
  },
  {
    id: "game_65",
    stage: "groups",
    group: "I",
    home_team_id: "FRA",
    away_team_id: "NOR",
    kickoff: "2026-06-26T16:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Boston (Boston)"
  },
  {
    id: "game_66",
    stage: "groups",
    group: "I",
    home_team_id: "SEN",
    away_team_id: "IRQ",
    kickoff: "2026-06-26T16:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Miami (Miami)"
  },
  {
    id: "game_67",
    stage: "groups",
    group: "L",
    home_team_id: "PAN",
    away_team_id: "ENG",
    kickoff: "2026-06-27T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Nova York/Nova Jersey (Nova York/Nova Jersey)"
  },
  {
    id: "game_68",
    stage: "groups",
    group: "L",
    home_team_id: "CRO",
    away_team_id: "GHA",
    kickoff: "2026-06-27T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio da Filadélfia (Filadélfia)"
  },
  {
    id: "game_69",
    stage: "groups",
    group: "J",
    home_team_id: "JOR",
    away_team_id: "ARG",
    kickoff: "2026-06-27T23:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Dallas (Dallas)"
  },
  {
    id: "game_70",
    stage: "groups",
    group: "J",
    home_team_id: "ALG",
    away_team_id: "AUT",
    kickoff: "2026-06-27T23:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Kansas City (Kansas City)"
  },
  {
    id: "game_71",
    stage: "groups",
    group: "K",
    home_team_id: "COL",
    away_team_id: "POR",
    kickoff: "2026-06-27T20:30:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Miami (Miami)"
  },
  {
    id: "game_72",
    stage: "groups",
    group: "K",
    home_team_id: "COD",
    away_team_id: "UZB",
    kickoff: "2026-06-27T20:30:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    stadium: "Estádio de Atlanta (Atlanta)"
  },
  {
    id: "game_73",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "1º Grupo E",
    placeholder_away: "3º Grupo A/B/C/D/F",
    next_match_id: "game_89",
    stadium: "A definir"
  },
  {
    id: "game_74",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "1º Grupo I",
    placeholder_away: "3º Grupo C/D/F/G/H",
    next_match_id: "game_89",
    stadium: "A definir"
  },
  {
    id: "game_75",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "2º Grupo A",
    placeholder_away: "2º Grupo B",
    next_match_id: "game_90",
    stadium: "A definir"
  },
  {
    id: "game_76",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "1º Grupo F",
    placeholder_away: "2º Grupo C",
    next_match_id: "game_90",
    stadium: "A definir"
  },
  {
    id: "game_77",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "2º Grupo K",
    placeholder_away: "2º Grupo L",
    next_match_id: "game_91",
    stadium: "A definir"
  },
  {
    id: "game_78",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "1º Grupo H",
    placeholder_away: "2º Grupo J",
    next_match_id: "game_91",
    stadium: "A definir"
  },
  {
    id: "game_79",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "1º Grupo D",
    placeholder_away: "3º Grupo B/E/F/I/J",
    next_match_id: "game_92",
    stadium: "A definir"
  },
  {
    id: "game_80",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "1º Grupo G",
    placeholder_away: "3º Grupo A/E/H/I/J",
    next_match_id: "game_92",
    stadium: "A definir"
  },
  {
    id: "game_81",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "1º Grupo C",
    placeholder_away: "2º Grupo F",
    next_match_id: "game_93",
    stadium: "A definir"
  },
  {
    id: "game_82",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "2º Grupo E",
    placeholder_away: "2º Grupo I",
    next_match_id: "game_93",
    stadium: "A definir"
  },
  {
    id: "game_83",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "1º Grupo A",
    placeholder_away: "3º Grupo C/E/F/H/I",
    next_match_id: "game_94",
    stadium: "A definir"
  },
  {
    id: "game_84",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "1º Grupo L",
    placeholder_away: "3º Grupo E/H/I/J/K",
    next_match_id: "game_94",
    stadium: "A definir"
  },
  {
    id: "game_85",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "1º Grupo J",
    placeholder_away: "2º Grupo H",
    next_match_id: "game_95",
    stadium: "A definir"
  },
  {
    id: "game_86",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "2º Grupo D",
    placeholder_away: "2º Grupo G",
    next_match_id: "game_95",
    stadium: "A definir"
  },
  {
    id: "game_87",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "1º Grupo B",
    placeholder_away: "3º Grupo E/F/G/I/J",
    next_match_id: "game_96",
    stadium: "A definir"
  },
  {
    id: "game_88",
    stage: "round_of_32",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-06-30T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "1º Grupo K",
    placeholder_away: "3º Grupo D/E/I/J/L",
    next_match_id: "game_96",
    stadium: "A definir"
  },
  {
    id: "game_89",
    stage: "round_of_16",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-04T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Chave 1",
    placeholder_away: "Vencedor Chave 2",
    next_match_id: "game_97",
    stadium: "A definir"
  },
  {
    id: "game_90",
    stage: "round_of_16",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-04T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Chave 3",
    placeholder_away: "Vencedor Chave 4",
    next_match_id: "game_97",
    stadium: "A definir"
  },
  {
    id: "game_91",
    stage: "round_of_16",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-04T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Chave 5",
    placeholder_away: "Vencedor Chave 6",
    next_match_id: "game_98",
    stadium: "A definir"
  },
  {
    id: "game_92",
    stage: "round_of_16",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-04T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Chave 7",
    placeholder_away: "Vencedor Chave 8",
    next_match_id: "game_98",
    stadium: "A definir"
  },
  {
    id: "game_93",
    stage: "round_of_16",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-04T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Chave 9",
    placeholder_away: "Vencedor Chave 10",
    next_match_id: "game_99",
    stadium: "A definir"
  },
  {
    id: "game_94",
    stage: "round_of_16",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-04T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Chave 11",
    placeholder_away: "Vencedor Chave 12",
    next_match_id: "game_99",
    stadium: "A definir"
  },
  {
    id: "game_95",
    stage: "round_of_16",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-04T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Chave 13",
    placeholder_away: "Vencedor Chave 14",
    next_match_id: "game_100",
    stadium: "A definir"
  },
  {
    id: "game_96",
    stage: "round_of_16",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-04T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Chave 15",
    placeholder_away: "Vencedor Chave 16",
    next_match_id: "game_100",
    stadium: "A definir"
  },
  {
    id: "game_97",
    stage: "quarterfinals",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-09T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Oitavas 1",
    placeholder_away: "Vencedor Oitavas 2",
    next_match_id: "game_101",
    stadium: "A definir"
  },
  {
    id: "game_98",
    stage: "quarterfinals",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-09T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Oitavas 3",
    placeholder_away: "Vencedor Oitavas 4",
    next_match_id: "game_101",
    stadium: "A definir"
  },
  {
    id: "game_99",
    stage: "quarterfinals",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-09T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Oitavas 5",
    placeholder_away: "Vencedor Oitavas 6",
    next_match_id: "game_102",
    stadium: "A definir"
  },
  {
    id: "game_100",
    stage: "quarterfinals",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-09T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Oitavas 7",
    placeholder_away: "Vencedor Oitavas 8",
    next_match_id: "game_102",
    stadium: "A definir"
  },
  {
    id: "game_101",
    stage: "semifinals",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-14T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Quartas 1",
    placeholder_away: "Vencedor Quartas 2",
    next_match_id: "game_104",
    stadium: "A definir"
  },
  {
    id: "game_102",
    stage: "semifinals",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-14T18:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Quartas 3",
    placeholder_away: "Vencedor Quartas 4",
    next_match_id: "game_104",
    stadium: "A definir"
  },
  {
    id: "game_103",
    stage: "third_place",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-18T15:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Perdedor Semifinal 1",
    placeholder_away: "Perdedor Semifinal 2",
    stadium: "A definir"
  },
  {
    id: "game_104",
    stage: "final",
    group: null,
    home_team_id: "",
    away_team_id: "",
    kickoff: "2026-07-19T15:00:00-03:00",
    home_score: null,
    away_score: null,
    status: "scheduled",
    placeholder_home: "Vencedor Semifinal 1",
    placeholder_away: "Vencedor Semifinal 2",
    stadium: "MetLife Stadium (New York/New Jersey)"
  }
];