import { Team } from "@/types";

export const STICKERS_PER_TEAM = 20;

export function getStickerCount(team: Team): number {
  return team.stickerCount ?? STICKERS_PER_TEAM;
}

export const MOCK_TEAMS: Team[] = [
  { id: "MEX", name: "México", code: "MEX", group: "A", flag: "🇲🇽" },
  { id: "RSA", name: "África do Sul", code: "RSA", group: "A", flag: "🇿🇦" },
  { id: "KOR", name: "Coreia do Sul", code: "KOR", group: "A", flag: "🇰🇷" },
  { id: "CZE", name: "Tchéquia", code: "CZE", group: "A", flag: "🇨🇿" },
  { id: "CAN", name: "Canadá", code: "CAN", group: "B", flag: "🇨🇦" },
  { id: "BIH", name: "Bósnia e Herzegovina", code: "BIH", group: "B", flag: "🇧🇦" },
  { id: "QAT", name: "Catar", code: "QAT", group: "B", flag: "🇶🇦" },
  { id: "SUI", name: "Suíça", code: "SUI", group: "B", flag: "🇨🇭" },
  { id: "BRA", name: "Brasil", code: "BRA", group: "C", flag: "🇧🇷" },
  { id: "MAR", name: "Marrocos", code: "MAR", group: "C", flag: "🇲🇦" },
  { id: "HAI", name: "Haiti", code: "HAI", group: "C", flag: "🇭🇹" },
  { id: "SCO", name: "Escócia", code: "SCO", group: "C", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "USA", name: "Estados Unidos", code: "USA", group: "D", flag: "🇺🇸" },
  { id: "PAR", name: "Paraguai", code: "PAR", group: "D", flag: "🇵🇾" },
  { id: "AUS", name: "Austrália", code: "AUS", group: "D", flag: "🇦🇺" },
  { id: "TUR", name: "Turquia", code: "TUR", group: "D", flag: "🇹🇷" },
  { id: "GER", name: "Alemanha", code: "GER", group: "E", flag: "🇩🇪" },
  { id: "CUW", name: "Curaçao", code: "CUW", group: "E", flag: "🇨🇼" },
  { id: "CIV", name: "Costa do Marfim", code: "CIV", group: "E", flag: "🇨🇮" },
  { id: "ECU", name: "Equador", code: "ECU", group: "E", flag: "🇪🇨" },
  { id: "NED", name: "Holanda", code: "NED", group: "F", flag: "🇳🇱" },
  { id: "JPN", name: "Japão", code: "JPN", group: "F", flag: "🇯🇵" },
  { id: "SWE", name: "Suécia", code: "SWE", group: "F", flag: "🇸🇪" },
  { id: "TUN", name: "Tunísia", code: "TUN", group: "F", flag: "🇹🇳" },
  { id: "BEL", name: "Bélgica", code: "BEL", group: "G", flag: "🇧🇪" },
  { id: "EGY", name: "Egito", code: "EGY", group: "G", flag: "🇪🇬" },
  { id: "IRN", name: "Irã", code: "IRN", group: "G", flag: "🇮🇷" },
  { id: "NZL", name: "Nova Zelândia", code: "NZL", group: "G", flag: "🇳🇿" },
  { id: "ESP", name: "Espanha", code: "ESP", group: "H", flag: "🇪🇸" },
  { id: "CPV", name: "Cabo Verde", code: "CPV", group: "H", flag: "🇨🇻" },
  { id: "KSA", name: "Arábia Saudita", code: "KSA", group: "H", flag: "🇸🇦" },
  { id: "URU", name: "Uruguai", code: "URU", group: "H", flag: "🇺🇾" },
  { id: "FRA", name: "França", code: "FRA", group: "I", flag: "🇫🇷" },
  { id: "SEN", name: "Senegal", code: "SEN", group: "I", flag: "🇸🇳" },
  { id: "NOR", name: "Noruega", code: "NOR", group: "I", flag: "🇳🇴" },
  { id: "IRQ", name: "Iraque", code: "IRQ", group: "I", flag: "🇮🇶" },
  { id: "ARG", name: "Argentina", code: "ARG", group: "J", flag: "🇦🇷" },
  { id: "ALG", name: "Argélia", code: "ALG", group: "J", flag: "🇩🇿" },
  { id: "AUT", name: "Áustria", code: "AUT", group: "J", flag: "🇦🇹" },
  { id: "JOR", name: "Jordânia", code: "JOR", group: "J", flag: "🇯🇴" },
  { id: "POR", name: "Portugal", code: "POR", group: "K", flag: "🇵🇹" },
  { id: "COD", name: "RD Congo", code: "COD", group: "K", flag: "🇨🇩" },
  { id: "UZB", name: "Uzbequistão", code: "UZB", group: "K", flag: "🇺🇿" },
  { id: "COL", name: "Colômbia", code: "COL", group: "K", flag: "🇨🇴" },
  { id: "ENG", name: "Inglaterra", code: "ENG", group: "L", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "CRO", name: "Croácia", code: "CRO", group: "L", flag: "🇭🇷" },
  { id: "GHA", name: "Gana", code: "GHA", group: "L", flag: "🇬🇭" },
  { id: "PAN", name: "Panamá", code: "PAN", group: "L", flag: "🇵🇦" },
  { id: "FWC", name: "FIFA", code: "FWC", group: "X", flag: "⚽", stickerCount: 18 },
  { id: "CC", name: "Coca-Cola", code: "CC", group: "X", flag: "🥤", stickerCount: 14 },
];
